---
Name: goldfinch-formhandler
After:
  - '#goldfinch-tinify'
  - '#goldfinch-instsupply'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Formhandler\Extensions\SiteConfigExtension
